### ISSUE TITLE
How to prepare the source.att file

### ISSUE THREAD

**Issue by boshuru** [may-/cnn-re-tf#2]
Hi there, I am back again. This time I am trying to train a context cnn model using sentence and some other attributes. For example, including sentence itself and demographic attributes of writer (age, income, education level, etc) into a source data entry: "The fox chase a bunny , 23 , 24000 , high school"

I am not quite sure whether I could just added these other attributes as left, right file, correct me if I am wrong:
>>source.left:
the fox chase a bunny
>>source.middle:
23,24000
>>source.right:
high school
>>target.txt
1 0

BUT how abount source.att? How to decide the values between 0.0 and 1.0?

**Comment by may-** [comment]
Hey,

> I am not quite sure whether I could just added these other attributes as left, right file, correct me if I am wrong:

Humm, I don't think my context-wise code suites your case. In my code, all contexts (left, right and middle) look up word embeddings, but in your case, you combine text input ("The fox chase a bunny") with numerical features ("23 , 24000") and categorical features ("high school"). And of course numerical and categorical features don't need word embeddings. So you can't reuse my code, you have to re-implement the layer for your non-textual features, I guess.


> BUT how abount source.att? How to decide the values between 0.0 and 1.0?

Yeah, this is a problem, how you get the attention. I derived this from some manual annotation (see: [`data/gold_annotation.tsv`](https://github.com/may-/cnn-re-tf/blob/master/data/gold_patterns.tsv), conversion into 0-1 value: [`score_reliability`](https://github.com/may-/cnn-re-tf/blob/master/distant_supervision.py#L546) function). 

But actually, attention values should be jointly learned during training, I mean, should not be given in advance. My attention implementation is fixed, just adds extra info to the loss. So, there are two options: (1) use some fixed manual annotation (like my code, which is not so good...) or (2) implement an attention layer to jointly learn the values (I don't have code for that, but it is desired in the actual sense of "attention")

Sorry, I can't help you for this topics...
