### ISSUE TITLE
Dataset format and input format for new predictions

### ISSUE THREAD

**Issue by ArijeetC** [may-/cnn-re-tf#5]
Hi, can you please explain how I can form my own dataset for training MLMICNN. I'm confused with the source.att and target files and some tokens in the other files, such as <Q13974>, <Q60>, etc.
Also is it possible to check the relation prediction for a single sentence after training is completed ?

**Comment by may-** [comment]
Hi,

Could you please refer [issue#1](https://github.com/may-/cnn-re-tf/issues/1) (how to check prediction) and [issue#2](https://github.com/may-/cnn-re-tf/issues/2) (how to create source.att), at first?

MLMI stands for multi-label multi-instance training, that is, the labels are not mutually exclusive.
My task is to predict the relationship between two entities. For example, if you have the entity pair:
```
Berlin <relation> Germany
```
then the correct prediction will be: [`country`](http://www.wikidata.org/prop/direct/P17), [`located_in`](http://www.wikidata.org/prop/direct/P131) and [`capital_of`](http://www.wikidata.org/prop/direct/P1376). (In this case, three correct labels according to [WikiData](https://query.wikidata.org/#SELECT%20DISTINCT%20%3Fp%20%3Fl%20%3Fs%0AWHERE%20%7B%0Awd%3AQ64%20%3Fp%20wd%3AQ183%20.%0A%3Fproperty%20%3Fref%20%3Fp%20.%0A%3Fproperty%20a%20wikibase%3AProperty%20.%0A%3Fproperty%20rdfs%3Alabel%20%3Fl%0AFILTER%20%28lang%28%3Fl%29%20%3D%20%22en%22%29.%0A%7D))

Let's say, I found the following sentence online:
```
The city of Berlin is located in eastern Germany on the River Spree. 
```

Then the training data looks like:
- `source.txt` ([`Berlin`](https://www.wikidata.org/wiki/Q64) has entity ID: \<Q64\>, [`Germany`](https://www.wikidata.org/wiki/Q183): \<Q183\>)

   ```
   The city of <Q64> is located in eastern <Q183> on the River Spree . 
   ```
- `source.left`

   ```
   The city of <Q64>
   ```
- `source.middle`

   ```
   is located in eastern
   ```
- `source.right`

   ```
   <Q183> on the River Spree . 
   ```

- `target.txt` (assume that the first column represents whether the sentence has the label `country`, second column: `located_in`, third column: `capital_of`, etc.)

   ```
   1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   ```

Here is the list of 23 labels (and the class-wise results):
![class-wise results](https://user-images.githubusercontent.com/5838079/29571648-07f84838-875a-11e7-9569-46c1ca96b5ae.jpg)


If you still have any questions, describe them little bit more concretely, please? I don't have any clue what your task is, how your data look like etc...

**Comment by ArijeetC** [comment]
Hi, thanks for the explanation. My task is also relationship extraction, I need to find the relations that exist in a given set of documents. I plan to first create a dataset from the documents with the entities and relations annotated, and then train a model on it to predict relations for new documents. Will this project be suitable for my task?

**Comment by may-** [comment]
It sounds pretty similar to my task. 
Ah, so, your question is how to do distant supervision, right?

I'm not sure if it helps, but I describe here the four steps I did in the `distant_supervision.py` script.

1. Download raw text data (if you already have the documents, you can replace this with your data)
   For example: 
    ```
    The city of Berlin is located in eastern Germany on the River Spree. 
    ```
2. Find entity
    - execute StanfordNER ([demo](http://nlp.stanford.edu:8080/ner/))
        ```
        The city of <Berlin_LOCATION> is located in eastern <Germany_LOCATION> on the <River Spree_LOCATION>. 
        ```
    - extract all combinations. In the case above:
        ```
        <Berlin_LOCATION> <Germany_LOCATION>
        <Berlin_LOCATION> <River Spree_LOCATION>
        <Germany_LOCATION> <River Spree_LOCATION>
        ```
3. Find entity ID (using SPARQL on WikiData API ([sample](https://query.wikidata.org/#SELECT%20DISTINCT%20%3Fitem%20%3Ffid%0AWHERE%20%7B%0A%20%20%3Fitem%20rdfs%3Alabel%20%22Germany%22%40en.%0A%20%20%3Fitem%20wdt%3AP31%20%3F_instanceOf.%0A%20%20%3F_instanceOf%20wdt%3AP279%2a%20wd%3AQ17334923.%0A%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP646%20%3Ffid.%20%7D%0A%7D)))
    ```
    <Q64 Berlin> <Q183 Germany>
    <Q64 Berlin> <Q1684 River Spree>
    <Q183 Germany> <Q1684 River Spree>
    ```
4. Find relation (using SPARQL on WikiData API ([sample](https://query.wikidata.org/#SELECT%20DISTINCT%20%3Fp%20%3Fl%20%3Fs%0AWHERE%20%7B%0Awd%3AQ64%20%3Fp%20wd%3AQ183%20.%0A%3Fproperty%20%3Fref%20%3Fp%20.%0A%3Fproperty%20a%20wikibase%3AProperty%20.%0A%3Fproperty%20rdfs%3Alabel%20%3Fl%0AFILTER%20%28lang%28%3Fl%29%20%3D%20%22en%22%29.%0A%7D)))
    ```
    <Q64 Berlin> <Q183 Germany> --> <P17 country>, <P1376 capital_of>, <P131 located_in>
    <Q64 Berlin> <Q1684 River Spree> --> <P206 located_next_to>
    <Q183 Germany> <Q1684 River Spree> --> None
    ```

At the end of these four steps, we get
- `source.txt`
```
The city of <Q64> is located in eastern <Q183> on the River Spree . 
The city of <Q64> is located in eastern Germany on the <Q1684> . 
```
and
- `target.txt`
```
1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

---

If you want to learn the theory, I recommend to read:
- Minz et al. [Distant supervision for relation extraction without labeled data](http://web.stanford.edu/~jurafsky/mintz.pdf) ACL 2009.
- Dong et al. [Knowledge Vault: A Web-Scale Approach to
Probabilistic Knowledge Fusion](https://www.cs.ubc.ca/~murphyk/Papers/kv-kdd14.pdf) ACM SIGKDD 2014.

**Comment by ArijeetC** [comment]
Thanks for the detailed explanation, I think I might be able to solve my task with this.
